//! AIR security: information flow analysis, taint tracking, security labels,
//! declassification, and sandbox enforcement.

use arc_effects::Effect;
use arc_ir::{Module, OperationKind};
use std::collections::{HashMap, HashSet};

// ---------------------------------------------------------------------------
// Security labels
// ---------------------------------------------------------------------------

/// Classification level for data flowing through an AIR program.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum SecurityLevel {
    /// Freely observable, no restrictions.
    Public,
    /// Internal use only, may not flow to external sinks.
    Internal,
    /// Sensitive data, requires explicit declassification.
    Confidential,
    /// Highest classification, never flows outside the trust boundary.
    Secret,
}

impl SecurityLevel {
    /// Returns true if `self` can flow into a sink at level `target` without
    /// declassification.
    pub fn can_flow_to(self, target: SecurityLevel) -> bool {
        // Higher-classified data cannot flow to lower-classified sinks.
        self <= target
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Public => "public",
            Self::Internal => "internal",
            Self::Confidential => "confidential",
            Self::Secret => "secret",
        }
    }

    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "public" => Some(Self::Public),
            "internal" => Some(Self::Internal),
            "confidential" => Some(Self::Confidential),
            "secret" => Some(Self::Secret),
            _ => None,
        }
    }
}

impl std::fmt::Display for SecurityLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

// ---------------------------------------------------------------------------
// Taint labels
// ---------------------------------------------------------------------------

/// A taint label tracking the provenance/trust of data.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum TaintLabel {
    /// Trusted program-internal data.
    Trusted,
    /// Data originating from user input.
    UserInput,
    /// Data from a third-party or external source.
    ThirdParty,
    /// Data generated by an LLM or model.
    ModelGenerated,
    /// Data from an untrusted network source.
    NetworkInput,
    /// Custom application-defined label.
    Custom(String),
}

impl TaintLabel {
    /// Returns true if this label represents untrusted data.
    pub fn is_untrusted(&self) -> bool {
        !matches!(self, Self::Trusted)
    }

    pub fn as_str(&self) -> &str {
        match self {
            Self::Trusted => "trusted",
            Self::UserInput => "user_input",
            Self::ThirdParty => "third_party",
            Self::ModelGenerated => "model_generated",
            Self::NetworkInput => "network_input",
            Self::Custom(s) => s.as_str(),
        }
    }

    pub fn parse(s: &str) -> Self {
        match s {
            "trusted" => Self::Trusted,
            "user_input" => Self::UserInput,
            "third_party" => Self::ThirdParty,
            "model_generated" => Self::ModelGenerated,
            "network_input" => Self::NetworkInput,
            other => Self::Custom(other.to_string()),
        }
    }
}

impl std::fmt::Display for TaintLabel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

// ---------------------------------------------------------------------------
// Security label map
// ---------------------------------------------------------------------------

/// Associates SSA values with security levels and taint labels.
#[derive(Debug, Clone, Default)]
pub struct SecurityContext {
    /// Classification level per value.
    levels: HashMap<String, SecurityLevel>,
    /// Taint labels per value (a value can carry multiple taints).
    taints: HashMap<String, HashSet<TaintLabel>>,
    /// Declassification proofs that have been verified.
    declassifications: HashSet<String>,
}

impl SecurityContext {
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the security level for a value.
    pub fn set_level(&mut self, value: &str, level: SecurityLevel) {
        self.levels.insert(value.to_string(), level);
    }

    /// Get the security level for a value, defaulting to Public if unknown.
    pub fn level(&self, value: &str) -> SecurityLevel {
        self.levels
            .get(value)
            .copied()
            .unwrap_or(SecurityLevel::Public)
    }

    /// Add a taint label to a value.
    pub fn add_taint(&mut self, value: &str, label: TaintLabel) {
        self.taints
            .entry(value.to_string())
            .or_default()
            .insert(label);
    }

    /// Get all taint labels for a value.
    pub fn taints(&self, value: &str) -> HashSet<TaintLabel> {
        self.taints.get(value).cloned().unwrap_or_default()
    }

    /// Returns true if the value has any untrusted taint.
    pub fn is_tainted(&self, value: &str) -> bool {
        self.taints
            .get(value)
            .map(|t| t.iter().any(|l| l.is_untrusted()))
            .unwrap_or(false)
    }

    /// Record a declassification proof for a value.
    pub fn add_declassification(&mut self, value: &str) {
        self.declassifications.insert(value.to_string());
    }

    /// Check if a value has been declassified.
    pub fn is_declassified(&self, value: &str) -> bool {
        self.declassifications.contains(value)
    }
}

// ---------------------------------------------------------------------------
// Sandbox policy
// ---------------------------------------------------------------------------

/// A sandbox policy restricting which capabilities a scope can access.
#[derive(Debug, Clone)]
pub struct SandboxPolicy {
    /// Capabilities explicitly allowed (exact names or glob patterns).
    allowed: HashSet<String>,
    /// Capabilities explicitly denied.
    denied: HashSet<String>,
    /// Maximum security level that may be accessed within the sandbox.
    max_level: SecurityLevel,
}

impl SandboxPolicy {
    pub fn new(max_level: SecurityLevel) -> Self {
        Self {
            allowed: HashSet::new(),
            denied: HashSet::new(),
            max_level,
        }
    }

    pub fn allow(&mut self, capability: impl Into<String>) {
        self.allowed.insert(capability.into());
    }

    pub fn deny(&mut self, capability: impl Into<String>) {
        self.denied.insert(capability.into());
    }

    /// Check if a capability is permitted under this sandbox.
    pub fn is_allowed(&self, capability: &str) -> bool {
        // Explicit deny takes priority.
        if self.is_denied(capability) {
            return false;
        }
        // If an allow-list exists, capability must be in it.
        if !self.allowed.is_empty() {
            return self.allowed.contains(capability);
        }
        true
    }

    /// Check if a capability or effect name is explicitly denied.
    pub fn is_denied(&self, name: &str) -> bool {
        if self.denied.contains(name) {
            return true;
        }
        for pattern in &self.denied {
            if let Some(prefix) = pattern.strip_suffix(".*") {
                if name.starts_with(prefix) {
                    return true;
                }
            }
        }
        false
    }

    /// Check if a security level is permitted within this sandbox.
    pub fn level_allowed(&self, level: SecurityLevel) -> bool {
        level <= self.max_level
    }
}

// ---------------------------------------------------------------------------
// Information-flow checker
// ---------------------------------------------------------------------------

/// Violations detected by the information-flow analysis.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SecurityViolation {
    /// Data at `source_level` was sent to a sink requiring `sink_level`.
    IllegalFlow {
        value: String,
        source_level: SecurityLevel,
        sink_level: SecurityLevel,
    },
    /// Tainted data was used in a privileged position (e.g., as an instruction).
    TaintedUse {
        value: String,
        taint: TaintLabel,
        context: String,
    },
    /// Capability invoked outside sandbox policy.
    SandboxViolation { capability: String, reason: String },
    /// Credential value leaked to a logging or tracing sink.
    CredentialLeak { value: String },
    /// Authority token used for a different resource than it was granted for.
    AuthorityMismatch {
        token: String,
        expected: String,
        actual: String,
    },
}

impl std::fmt::Display for SecurityViolation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::IllegalFlow {
                value,
                source_level,
                sink_level,
            } => write!(
                f,
                "illegal flow: {} ({}) -> {} sink",
                value, source_level, sink_level
            ),
            Self::TaintedUse {
                value,
                taint,
                context,
            } => write!(
                f,
                "tainted value {} ({}) used in privileged context: {}",
                value, taint, context
            ),
            Self::SandboxViolation { capability, reason } => {
                write!(f, "sandbox violation: {} — {}", capability, reason)
            }
            Self::CredentialLeak { value } => {
                write!(f, "credential value {} leaked to sink", value)
            }
            Self::AuthorityMismatch {
                token,
                expected,
                actual,
            } => write!(
                f,
                "authority mismatch: {} granted for {}, used for {}",
                token, expected, actual
            ),
        }
    }
}

/// Run information-flow analysis on a module.
///
/// This performs a forward dataflow pass over each function, propagating
/// security levels and taint labels through operations, and checking that
/// no data flows to a lower-classified sink without declassification.
pub fn check_information_flow(
    module: &Module,
    ctx: &SecurityContext,
    sandbox: Option<&SandboxPolicy>,
) -> Vec<SecurityViolation> {
    let mut violations = Vec::new();

    for (_name, func) in &module.functions {
        // Build per-value security level map for this function, starting from
        // the context's annotations and propagating through operations.
        let mut levels: HashMap<String, SecurityLevel> = HashMap::new();
        let mut taints: HashMap<String, HashSet<TaintLabel>> = HashMap::new();

        // Seed from function parameters.
        for param in &func.params {
            let v = param.name.as_str().to_string();
            levels.insert(v.clone(), ctx.level(&v));
            let t = ctx.taints(&v);
            if !t.is_empty() {
                taints.insert(v, t);
            }
        }

        for block in &func.blocks {
            for arg in &block.args {
                let v = arg.name.as_str().to_string();
                levels.insert(v.clone(), ctx.level(&v));
                let t = ctx.taints(&v);
                if !t.is_empty() {
                    taints.insert(v, t);
                }
            }

            for op in &block.ops {
                // Propagate: result inherits the max level of all operands.
                let operand_level = op
                    .operands
                    .iter()
                    .map(|o| {
                        levels
                            .get(o.as_str())
                            .copied()
                            .unwrap_or(SecurityLevel::Public)
                    })
                    .max()
                    .unwrap_or(SecurityLevel::Public);

                // Merge taints from all operands.
                let mut merged_taints: HashSet<TaintLabel> = HashSet::new();
                for o in &op.operands {
                    if let Some(t) = taints.get(o.as_str()) {
                        merged_taints.extend(t.iter().cloned());
                    }
                }

                for result in &op.results {
                    let result_name = result.as_str();
                    let result_level = std::cmp::max(operand_level, ctx.level(result_name));
                    levels.insert(result_name.to_string(), result_level);

                    let mut result_taints = merged_taints.clone();
                    result_taints.extend(ctx.taints(result_name));
                    if !result_taints.is_empty() {
                        taints.insert(result_name.to_string(), result_taints);
                    }
                }

                // Check capability invocations against sandbox.
                if let OperationKind::Invoke { capability } = &op.kind {
                    let cap_name = capability.as_str();

                    let effective_effects = operation_effects(module, op);

                    if let Some(policy) = sandbox {
                        if !policy.is_allowed(cap_name) {
                            violations.push(SecurityViolation::SandboxViolation {
                                capability: cap_name.to_string(),
                                reason: "capability not permitted by sandbox policy".to_string(),
                            });
                        }
                        for effect in &effective_effects {
                            if policy.is_denied(effect) {
                                violations.push(SecurityViolation::SandboxViolation {
                                    capability: cap_name.to_string(),
                                    reason: format!(
                                        "effect {} is denied by sandbox policy",
                                        effect
                                    ),
                                });
                            }
                        }
                    }

                    // External effects on confidential+ data is an illegal flow
                    // to a public sink (the external world).
                    if has_external_effects(&effective_effects) {
                        for operand in &op.operands {
                            let lev = levels
                                .get(operand.as_str())
                                .copied()
                                .unwrap_or(SecurityLevel::Public);
                            if lev > SecurityLevel::Public && !ctx.is_declassified(operand.as_str())
                            {
                                violations.push(SecurityViolation::IllegalFlow {
                                    value: operand.as_str().to_string(),
                                    source_level: lev,
                                    sink_level: SecurityLevel::Public,
                                });
                            }
                        }
                    }

                    // Credential effect check: credential data should not flow to
                    // logging/tracing sinks.
                    if effective_effects.iter().any(|e| e.as_str() == "credential") {
                        for operand in &op.operands {
                            let lev = levels
                                .get(operand.as_str())
                                .copied()
                                .unwrap_or(SecurityLevel::Public);
                            if lev >= SecurityLevel::Confidential {
                                violations.push(SecurityViolation::CredentialLeak {
                                    value: operand.as_str().to_string(),
                                });
                            }
                        }
                    }
                }

                // Taint check: model-generated or third-party content used as
                // an authority/instruction operand in RequireApproval.
                if matches!(op.kind, OperationKind::RequireApproval) {
                    for operand in &op.operands {
                        if let Some(t) = taints.get(operand.as_str()) {
                            for label in t {
                                if label.is_untrusted() {
                                    violations.push(SecurityViolation::TaintedUse {
                                        value: operand.as_str().to_string(),
                                        taint: label.clone(),
                                        context: "require_approval instruction".to_string(),
                                    });
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    violations
}

/// Check if a set of effect strings contains any external effect.
fn has_external_effects(effects: &[String]) -> bool {
    for e in effects {
        // Parse "#arc.effect<...>" or bare effect names.
        let name = if let Some(inner) = e.strip_prefix("#arc.effect<") {
            inner.strip_suffix('>').unwrap_or(inner)
        } else {
            e.as_str()
        };
        if let Some(eff) = Effect::parse(name) {
            if eff.is_external() {
                return true;
            }
        }
    }
    false
}

fn operation_effects(module: &Module, op: &arc_ir::Operation) -> Vec<String> {
    let mut effects = op.effects.clone();
    if let OperationKind::Invoke { capability } = &op.kind {
        if let Some(cap) = module.capabilities.get(capability) {
            for effect in &cap.effects {
                if !effects.contains(effect) {
                    effects.push(effect.clone());
                }
            }
        }
    }
    effects
}

// ---------------------------------------------------------------------------
// Taint propagation analysis (standalone)
// ---------------------------------------------------------------------------

/// Compute the set of tainted values reachable from initial taint sources.
/// Returns a map from value name to the set of taint labels it carries.
pub fn propagate_taints(
    module: &Module,
    sources: &HashMap<String, TaintLabel>,
) -> HashMap<String, HashSet<TaintLabel>> {
    let mut taints: HashMap<String, HashSet<TaintLabel>> = HashMap::new();

    for (val, label) in sources {
        taints.entry(val.clone()).or_default().insert(label.clone());
    }

    for (_name, func) in &module.functions {
        // Seed params.
        for param in &func.params {
            let v = param.name.as_str().to_string();
            if let Some(label) = sources.get(&v) {
                taints.entry(v).or_default().insert(label.clone());
            }
        }

        for block in &func.blocks {
            for op in &block.ops {
                let mut merged: HashSet<TaintLabel> = HashSet::new();
                for operand in &op.operands {
                    if let Some(t) = taints.get(operand.as_str()) {
                        merged.extend(t.iter().cloned());
                    }
                }
                if !merged.is_empty() {
                    for result in &op.results {
                        taints
                            .entry(result.as_str().to_string())
                            .or_default()
                            .extend(merged.iter().cloned());
                    }
                }
            }
        }
    }

    taints
}

// ---------------------------------------------------------------------------
// Capability attenuation
// ---------------------------------------------------------------------------

/// An attenuated capability: a capability that has been narrowed in scope.
#[derive(Debug, Clone)]
pub struct AttenuatedCapability {
    /// The original capability name.
    pub original: String,
    /// Restricted operations (subset of the original's operations).
    pub allowed_operations: HashSet<String>,
    /// Maximum data level that may pass through.
    pub max_data_level: SecurityLevel,
}

impl AttenuatedCapability {
    pub fn new(original: impl Into<String>, max_level: SecurityLevel) -> Self {
        Self {
            original: original.into(),
            allowed_operations: HashSet::new(),
            max_data_level: max_level,
        }
    }

    pub fn allow_operation(&mut self, op: impl Into<String>) {
        self.allowed_operations.insert(op.into());
    }

    /// Validate that an invocation is within the attenuated scope.
    pub fn validate(&self, operation: &str, data_level: SecurityLevel) -> Result<(), String> {
        if !self.allowed_operations.is_empty() && !self.allowed_operations.contains(operation) {
            return Err(format!(
                "operation '{}' not permitted by attenuated capability '{}'",
                operation, self.original
            ));
        }
        if !data_level.can_flow_to(self.max_data_level) {
            return Err(format!(
                "data level {} exceeds attenuated capability max level {}",
                data_level, self.max_data_level
            ));
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Module-level security audit
// ---------------------------------------------------------------------------

/// Summary of a module's security posture.
#[derive(Debug)]
pub struct SecurityAudit {
    /// Total number of capability invocations.
    pub capability_invocations: usize,
    /// Total number of approval requests.
    pub approval_requests: usize,
    /// Capabilities invoked.
    pub capabilities_used: HashSet<String>,
    /// Whether any operation has external effects.
    pub has_external_effects: bool,
    /// Whether any operation handles credentials.
    pub handles_credentials: bool,
    /// Violations found.
    pub violations: Vec<SecurityViolation>,
}

/// Audit a module for security properties.
pub fn audit_module(
    module: &Module,
    ctx: &SecurityContext,
    sandbox: Option<&SandboxPolicy>,
) -> SecurityAudit {
    let mut audit = SecurityAudit {
        capability_invocations: 0,
        approval_requests: 0,
        capabilities_used: HashSet::new(),
        has_external_effects: false,
        handles_credentials: false,
        violations: Vec::new(),
    };

    for (_name, func) in &module.functions {
        for block in &func.blocks {
            for op in &block.ops {
                match &op.kind {
                    OperationKind::Invoke { capability } => {
                        audit.capability_invocations += 1;
                        audit
                            .capabilities_used
                            .insert(capability.as_str().to_string());
                    }
                    OperationKind::RequireApproval => {
                        audit.approval_requests += 1;
                    }
                    _ => {}
                }

                let effects = operation_effects(module, op);
                if has_external_effects(&effects) {
                    audit.has_external_effects = true;
                }
                if effects.iter().any(|e| e.contains("credential")) {
                    audit.handles_credentials = true;
                }
            }
        }
    }

    audit.violations = check_information_flow(module, ctx, sandbox);
    audit
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use arc_ir::*;

    fn loc() -> Location {
        Location::new(0, 0)
    }

    fn make_module_with_invoke(cap_name: &str, effects: Vec<&str>) -> Module {
        let mut module = Module::new(Symbol::new("test"));
        let cap = Capability {
            name: Symbol::new(cap_name),
            inputs: vec![Argument {
                name: ValueId::new("data"),
                ty: Type::new("i64"),
                location: loc(),
            }],
            outputs: vec![],
            effects: effects.iter().map(|e| e.to_string()).collect(),
            failures: vec![],
            location: loc(),
        };
        module.add_capability(cap).unwrap();

        let mut func = Function::new(
            Symbol::new("main"),
            vec![],
            vec![Argument {
                name: ValueId::new("data"),
                ty: Type::new("i64"),
                location: loc(),
            }],
            None,
            loc(),
        );
        let mut block = Block::new(Some("entry".into()), loc());
        block.add_op(Operation {
            results: vec![],
            kind: OperationKind::Invoke {
                capability: Symbol::new(cap_name),
            },
            operands: vec![ValueId::new("data")],
            result_types: vec![],
            effects: effects.iter().map(|e| e.to_string()).collect(),
            location: loc(),
            regions: vec![],
        });
        block.add_op(Operation {
            results: vec![],
            kind: OperationKind::Return,
            operands: vec![],
            result_types: vec![],
            effects: vec![],
            location: loc(),
            regions: vec![],
        });
        func.add_block(block);
        module.add_function(func).unwrap();
        module
    }

    #[test]
    fn security_level_ordering() {
        assert!(SecurityLevel::Public.can_flow_to(SecurityLevel::Confidential));
        assert!(SecurityLevel::Public.can_flow_to(SecurityLevel::Public));
        assert!(!SecurityLevel::Secret.can_flow_to(SecurityLevel::Public));
        assert!(!SecurityLevel::Confidential.can_flow_to(SecurityLevel::Internal));
    }

    #[test]
    fn security_level_roundtrip() {
        for level in [
            SecurityLevel::Public,
            SecurityLevel::Internal,
            SecurityLevel::Confidential,
            SecurityLevel::Secret,
        ] {
            assert_eq!(SecurityLevel::parse(level.as_str()), Some(level));
        }
    }

    #[test]
    fn taint_label_untrusted() {
        assert!(!TaintLabel::Trusted.is_untrusted());
        assert!(TaintLabel::UserInput.is_untrusted());
        assert!(TaintLabel::ThirdParty.is_untrusted());
        assert!(TaintLabel::ModelGenerated.is_untrusted());
        assert!(TaintLabel::NetworkInput.is_untrusted());
    }

    #[test]
    fn taint_label_roundtrip() {
        for label in [
            "trusted",
            "user_input",
            "third_party",
            "model_generated",
            "network_input",
        ] {
            let parsed = TaintLabel::parse(label);
            assert_eq!(parsed.as_str(), label);
        }
    }

    #[test]
    fn sandbox_allow_deny() {
        let mut policy = SandboxPolicy::new(SecurityLevel::Internal);
        policy.allow("spreadsheet.read");
        policy.deny("network.*");
        policy.deny("filesystem.write");

        assert!(policy.is_allowed("spreadsheet.read"));
        assert!(!policy.is_allowed("network.send"));
        assert!(!policy.is_allowed("network.connect"));
        assert!(!policy.is_allowed("filesystem.write"));
        // Not in allow list:
        assert!(!policy.is_allowed("email.send"));
    }

    #[test]
    fn sandbox_level_check() {
        let policy = SandboxPolicy::new(SecurityLevel::Internal);
        assert!(policy.level_allowed(SecurityLevel::Public));
        assert!(policy.level_allowed(SecurityLevel::Internal));
        assert!(!policy.level_allowed(SecurityLevel::Confidential));
        assert!(!policy.level_allowed(SecurityLevel::Secret));
    }

    #[test]
    fn illegal_flow_confidential_to_external() {
        let module = make_module_with_invoke("email.send", vec!["external_communication"]);
        let mut ctx = SecurityContext::new();
        ctx.set_level("data", SecurityLevel::Confidential);

        let violations = check_information_flow(&module, &ctx, None);
        assert_eq!(violations.len(), 1);
        assert!(matches!(
            &violations[0],
            SecurityViolation::IllegalFlow {
                source_level: SecurityLevel::Confidential,
                sink_level: SecurityLevel::Public,
                ..
            }
        ));
    }

    #[test]
    fn declassified_flow_is_allowed() {
        let module = make_module_with_invoke("email.send", vec!["external_communication"]);
        let mut ctx = SecurityContext::new();
        ctx.set_level("data", SecurityLevel::Confidential);
        ctx.add_declassification("data");

        let violations = check_information_flow(&module, &ctx, None);
        assert!(violations.is_empty());
    }

    #[test]
    fn public_data_flows_freely() {
        let module = make_module_with_invoke("email.send", vec!["external_communication"]);
        let ctx = SecurityContext::new(); // default Public

        let violations = check_information_flow(&module, &ctx, None);
        assert!(violations.is_empty());
    }

    #[test]
    fn sandbox_blocks_capability() {
        let module = make_module_with_invoke("network.send", vec!["network"]);
        let ctx = SecurityContext::new();
        let mut sandbox = SandboxPolicy::new(SecurityLevel::Public);
        sandbox.deny("network.*");

        let violations = check_information_flow(&module, &ctx, Some(&sandbox));
        assert!(!violations.is_empty());
        assert!(matches!(
            &violations[0],
            SecurityViolation::SandboxViolation { .. }
        ));
    }

    #[test]
    fn tainted_approval_operand_detected() {
        let mut module = Module::new(Symbol::new("test"));
        let mut func = Function::new(
            Symbol::new("main"),
            vec![],
            vec![Argument {
                name: ValueId::new("goal"),
                ty: Type::new("i64"),
                location: loc(),
            }],
            None,
            loc(),
        );
        let mut block = Block::new(Some("entry".into()), loc());
        block.add_op(Operation {
            results: vec![ValueId::new("auth")],
            kind: OperationKind::RequireApproval,
            operands: vec![ValueId::new("goal")],
            result_types: vec![Type::new("!arc.auth<action>")],
            effects: vec![],
            location: loc(),
            regions: vec![],
        });
        block.add_op(Operation {
            results: vec![],
            kind: OperationKind::Return,
            operands: vec![],
            result_types: vec![],
            effects: vec![],
            location: loc(),
            regions: vec![],
        });
        func.add_block(block);
        module.add_function(func).unwrap();

        let mut ctx = SecurityContext::new();
        ctx.add_taint("goal", TaintLabel::ThirdParty);

        let violations = check_information_flow(&module, &ctx, None);
        assert_eq!(violations.len(), 1);
        assert!(matches!(
            &violations[0],
            SecurityViolation::TaintedUse {
                taint: TaintLabel::ThirdParty,
                ..
            }
        ));
    }

    #[test]
    fn taint_propagation_through_ops() {
        let mut module = Module::new(Symbol::new("test"));
        let mut func = Function::new(
            Symbol::new("main"),
            vec![],
            vec![
                Argument {
                    name: ValueId::new("a"),
                    ty: Type::new("i64"),
                    location: loc(),
                },
                Argument {
                    name: ValueId::new("b"),
                    ty: Type::new("i64"),
                    location: loc(),
                },
            ],
            Some(Type::new("i64")),
            loc(),
        );
        let mut block = Block::new(Some("entry".into()), loc());
        block.add_op(Operation {
            results: vec![ValueId::new("c")],
            kind: OperationKind::Add,
            operands: vec![ValueId::new("a"), ValueId::new("b")],
            result_types: vec![Type::new("i64")],
            effects: vec![],
            location: loc(),
            regions: vec![],
        });
        block.add_op(Operation {
            results: vec![],
            kind: OperationKind::Return,
            operands: vec![ValueId::new("c")],
            result_types: vec![],
            effects: vec![],
            location: loc(),
            regions: vec![],
        });
        func.add_block(block);
        module.add_function(func).unwrap();

        let mut sources = HashMap::new();
        sources.insert("a".to_string(), TaintLabel::UserInput);

        let result = propagate_taints(&module, &sources);

        // "a" is tainted, "b" is not, but "c = a + b" should inherit taint from "a".
        assert!(result.get("a").unwrap().contains(&TaintLabel::UserInput));
        assert!(!result.contains_key("b"));
        assert!(result.get("c").unwrap().contains(&TaintLabel::UserInput));
    }

    #[test]
    fn attenuated_capability_validation() {
        let mut cap = AttenuatedCapability::new("spreadsheet", SecurityLevel::Internal);
        cap.allow_operation("read_range");
        cap.allow_operation("read_cell");

        assert!(cap.validate("read_range", SecurityLevel::Public).is_ok());
        assert!(cap.validate("read_cell", SecurityLevel::Internal).is_ok());
        assert!(cap.validate("write_cell", SecurityLevel::Public).is_err());
        assert!(cap
            .validate("read_range", SecurityLevel::Confidential)
            .is_err());
    }

    #[test]
    fn audit_module_counts() {
        let module = make_module_with_invoke("email.send", vec!["external_communication"]);
        let ctx = SecurityContext::new();
        let audit = audit_module(&module, &ctx, None);

        assert_eq!(audit.capability_invocations, 1);
        assert_eq!(audit.approval_requests, 0);
        assert!(audit.capabilities_used.contains("email.send"));
        assert!(audit.has_external_effects);
    }

    #[test]
    fn security_context_defaults() {
        let ctx = SecurityContext::new();
        assert_eq!(ctx.level("unknown"), SecurityLevel::Public);
        assert!(!ctx.is_tainted("unknown"));
        assert!(!ctx.is_declassified("unknown"));
    }

    #[test]
    fn multiple_taints_merge() {
        let mut ctx = SecurityContext::new();
        ctx.add_taint("v", TaintLabel::UserInput);
        ctx.add_taint("v", TaintLabel::ModelGenerated);
        let t = ctx.taints("v");
        assert_eq!(t.len(), 2);
        assert!(t.contains(&TaintLabel::UserInput));
        assert!(t.contains(&TaintLabel::ModelGenerated));
    }
}
