//! Document dialect: typed document spans, provenance, and trust labels.

use std::fmt;

/// Trust level of document content.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum TrustLevel {
    /// Untrusted content from external/unknown sources.
    Untrusted,
    /// Content from a known but unverified source.
    ThirdParty,
    /// Content generated by a model.
    ModelGenerated,
    /// Content from a trusted internal source.
    Trusted,
    /// User-verified content.
    Verified,
}

impl TrustLevel {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Untrusted => "untrusted",
            Self::ThirdParty => "third_party",
            Self::ModelGenerated => "model_generated",
            Self::Trusted => "trusted",
            Self::Verified => "verified",
        }
    }

    /// Whether this trust level can be used as an instruction source.
    pub fn can_instruct(self) -> bool {
        matches!(self, Self::Trusted | Self::Verified)
    }
}

impl fmt::Display for TrustLevel {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A span within a document.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Span {
    pub start: usize,
    pub end: usize,
    pub source: String,
    pub trust: TrustLevel,
}

impl Span {
    pub fn new(start: usize, end: usize, source: impl Into<String>, trust: TrustLevel) -> Self {
        Self {
            start,
            end,
            source: source.into(),
            trust,
        }
    }

    pub fn length(&self) -> usize {
        self.end - self.start
    }

    pub fn overlaps(&self, other: &Span) -> bool {
        self.source == other.source && self.start < other.end && other.start < self.end
    }
}

/// A document with typed content and provenance.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Document {
    pub content: String,
    pub spans: Vec<Span>,
    pub classification: String,
}

impl Document {
    pub fn new(content: impl Into<String>, classification: impl Into<String>) -> Self {
        Self {
            content: content.into(),
            spans: Vec::new(),
            classification: classification.into(),
        }
    }

    pub fn add_span(&mut self, span: Span) {
        self.spans.push(span);
    }

    /// Get the minimum trust level across all spans.
    pub fn min_trust(&self) -> TrustLevel {
        self.spans
            .iter()
            .map(|s| s.trust)
            .min()
            .unwrap_or(TrustLevel::Untrusted)
    }

    /// Check if any span contains untrusted content.
    pub fn has_untrusted_content(&self) -> bool {
        self.spans.iter().any(|s| s.trust == TrustLevel::Untrusted)
    }

    /// Check if the document is safe to use as instruction input.
    pub fn safe_for_instruction(&self) -> bool {
        self.spans.iter().all(|s| s.trust.can_instruct())
    }

    /// Extract spans from the same source.
    pub fn spans_from_source(&self, source: &str) -> Vec<&Span> {
        self.spans.iter().filter(|s| s.source == source).collect()
    }
}

/// Document operation for the AIR document dialect.
#[derive(Debug, Clone, PartialEq)]
pub enum DocOp {
    /// Extract relevant spans from a document.
    ExtractRelevant { doc: String, query: String },
    /// Merge multiple documents.
    Merge { docs: Vec<String> },
    /// Redact sensitive content.
    Redact { doc: String, patterns: Vec<String> },
    /// Summarize (via model), output is model_generated trust.
    Summarize { doc: String },
    /// Verify provenance chain.
    VerifyProvenance { doc: String },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn trust_level_ordering() {
        assert!(TrustLevel::Untrusted < TrustLevel::Verified);
        assert!(TrustLevel::ThirdParty < TrustLevel::Trusted);
        assert!(TrustLevel::ModelGenerated < TrustLevel::Trusted);
    }

    #[test]
    fn trust_level_instruction() {
        assert!(!TrustLevel::Untrusted.can_instruct());
        assert!(!TrustLevel::ThirdParty.can_instruct());
        assert!(!TrustLevel::ModelGenerated.can_instruct());
        assert!(TrustLevel::Trusted.can_instruct());
        assert!(TrustLevel::Verified.can_instruct());
    }

    #[test]
    fn span_overlap() {
        let a = Span::new(0, 10, "doc1", TrustLevel::Trusted);
        let b = Span::new(5, 15, "doc1", TrustLevel::Trusted);
        let c = Span::new(10, 20, "doc1", TrustLevel::Trusted);
        let d = Span::new(0, 10, "doc2", TrustLevel::Trusted);

        assert!(a.overlaps(&b));
        assert!(!a.overlaps(&c)); // adjacent, not overlapping
        assert!(!a.overlaps(&d)); // different source
    }

    #[test]
    fn document_trust_check() {
        let mut doc = Document::new("hello world", "internal");
        doc.add_span(Span::new(0, 5, "user", TrustLevel::Trusted));
        doc.add_span(Span::new(6, 11, "model", TrustLevel::ModelGenerated));

        assert!(!doc.safe_for_instruction());
        assert_eq!(doc.min_trust(), TrustLevel::ModelGenerated);
    }

    #[test]
    fn document_all_trusted() {
        let mut doc = Document::new("safe content", "public");
        doc.add_span(Span::new(0, 12, "admin", TrustLevel::Verified));

        assert!(doc.safe_for_instruction());
        assert!(!doc.has_untrusted_content());
    }

    #[test]
    fn document_untrusted_detection() {
        let mut doc = Document::new("injected content", "public");
        doc.add_span(Span::new(0, 16, "email", TrustLevel::Untrusted));

        assert!(doc.has_untrusted_content());
        assert!(!doc.safe_for_instruction());
    }

    #[test]
    fn spans_by_source() {
        let mut doc = Document::new("mixed sources", "internal");
        doc.add_span(Span::new(0, 5, "src_a", TrustLevel::Trusted));
        doc.add_span(Span::new(6, 13, "src_b", TrustLevel::ThirdParty));
        doc.add_span(Span::new(0, 3, "src_a", TrustLevel::Trusted));

        let from_a = doc.spans_from_source("src_a");
        assert_eq!(from_a.len(), 2);
    }
}
