//! Differential testing, fuzz testing, and conformance suite.
//!
//! - **Diff testing**: runs the same AIR program through both the reference
//!   interpreter and the x86_64 native code generator, then compares results.
//! - **Fuzz testing**: pseudo-random program generation + property checks
//!   (no panics, deterministic errors, round-trip stability).
//! - **Conformance suite**: canonical programs every AIR implementation must
//!   accept, reject, or compute identically.

pub mod conformance;
pub mod fuzz;
#[cfg(test)]
pub mod integration;

use arc_codegen::low_ir;
use arc_codegen::{isel, regalloc};
use arc_interp::run_main;
use arc_ir::Module;
use arc_syntax::parse_module;
use arc_targets::x86_64;
use arc_verify::verify_module;

/// Result of a differential test.
#[derive(Debug)]
pub struct DiffResult {
    pub program: String,
    pub interp_result: Option<i64>,
    pub native_result: Option<i64>,
    pub match_: bool,
}

/// Run a differential test on an AIR source program.
/// Returns the comparison result, or an error if either path fails.
pub fn diff_test(source: &str) -> Result<DiffResult, String> {
    let module = parse_module(source).map_err(|e| format!("parse error: {}", e))?;
    verify_module(&module).map_err(|e| format!("verify error: {}", e))?;

    let interp_result = run_main(&module).map_err(|e| format!("interp error: {}", e))?;

    let native_result = jit_run(&module)?;

    let match_ = interp_result == native_result;
    Ok(DiffResult {
        program: source.to_string(),
        interp_result,
        native_result,
        match_,
    })
}

/// JIT-compile and execute the @main function of a module.
fn jit_run(module: &Module) -> Result<Option<i64>, String> {
    let target = x86_64::target();

    // Lower to low IR
    let low_module = low_ir::lower_module(module).map_err(|e| format!("lowering error: {}", e))?;

    // Find main function
    let main_func = low_module
        .functions
        .iter()
        .find(|f| f.name == "main")
        .ok_or_else(|| "no main function in low IR".to_string())?;

    // Instruction selection
    let mut mfunc =
        isel::select_instructions(main_func, &target).map_err(|e| format!("isel error: {}", e))?;

    // Register allocation
    regalloc::allocate_registers(&mut mfunc, &target)
        .map_err(|e| format!("regalloc error: {}", e))?;

    // Emit machine code
    let obj = arc_codegen::emit::emit_object(&[mfunc], &target)
        .map_err(|e| format!("emit error: {}", e))?;

    // JIT execute
    let result = unsafe { jit_execute(&obj.text) }?;
    Ok(Some(result))
}

/// Map machine code into executable memory and call it as a function returning i64.
///
/// # Safety
/// Executes arbitrary machine code. Only safe when the code is generated by our compiler.
unsafe fn jit_execute(code: &[u8]) -> Result<i64, String> {
    let page_size = unsafe { libc::sysconf(libc::_SC_PAGESIZE) } as usize;
    let size = code.len().div_ceil(page_size) * page_size;

    let ptr = unsafe {
        libc::mmap(
            std::ptr::null_mut(),
            size,
            libc::PROT_READ | libc::PROT_WRITE,
            libc::MAP_PRIVATE | libc::MAP_ANONYMOUS,
            -1,
            0,
        )
    };

    if ptr == libc::MAP_FAILED {
        return Err("mmap failed".to_string());
    }

    // Copy code
    unsafe {
        std::ptr::copy_nonoverlapping(code.as_ptr(), ptr as *mut u8, code.len());
    }

    // Make executable
    let ret = unsafe { libc::mprotect(ptr, size, libc::PROT_READ | libc::PROT_EXEC) };
    if ret != 0 {
        unsafe {
            libc::munmap(ptr, size);
        }
        return Err("mprotect failed".to_string());
    }

    // Call as fn() -> i64
    let func: extern "C" fn() -> i64 = unsafe { std::mem::transmute(ptr) };
    let result = func();

    // Cleanup
    unsafe {
        libc::munmap(ptr, size);
    }

    Ok(result)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn diff_const_return() {
        let result = diff_test(
            "\
arc.module @m {
  arc.func @main() -> i64 {
  ^entry:
    %v = arc.const 42 : i64
    arc.return %v : i64
  }
}
",
        )
        .unwrap();
        assert!(
            result.match_,
            "interp={:?} native={:?}",
            result.interp_result, result.native_result
        );
        assert_eq!(result.interp_result, Some(42));
        assert_eq!(result.native_result, Some(42));
    }

    #[test]
    fn diff_add() {
        let result = diff_test(
            "\
arc.module @m {
  arc.func @main() -> i64 {
  ^entry:
    %a = arc.const 3 : i64
    %b = arc.const 7 : i64
    %c = arc.add %a, %b : i64
    arc.return %c : i64
  }
}
",
        )
        .unwrap();
        assert!(result.match_);
        assert_eq!(result.interp_result, Some(10));
    }

    #[test]
    fn diff_sub() {
        let result = diff_test(
            "\
arc.module @m {
  arc.func @main() -> i64 {
  ^entry:
    %a = arc.const 100 : i64
    %b = arc.const 37 : i64
    %c = arc.sub %a, %b : i64
    arc.return %c : i64
  }
}
",
        )
        .unwrap();
        assert!(result.match_);
        assert_eq!(result.interp_result, Some(63));
    }

    #[test]
    fn diff_mul() {
        let result = diff_test(
            "\
arc.module @m {
  arc.func @main() -> i64 {
  ^entry:
    %a = arc.const 6 : i64
    %b = arc.const 7 : i64
    %c = arc.mul %a, %b : i64
    arc.return %c : i64
  }
}
",
        )
        .unwrap();
        assert!(result.match_);
        assert_eq!(result.interp_result, Some(42));
    }

    #[test]
    fn diff_nested_arithmetic() {
        let result = diff_test(
            "\
arc.module @m {
  arc.func @main() -> i64 {
  ^entry:
    %a = arc.const 2 : i64
    %b = arc.const 3 : i64
    %c = arc.const 4 : i64
    %ab = arc.mul %a, %b : i64
    %abc = arc.add %ab, %c : i64
    arc.return %abc : i64
  }
}
",
        )
        .unwrap();
        assert!(result.match_);
        assert_eq!(result.interp_result, Some(10)); // 2*3 + 4
    }

    #[test]
    fn diff_negative_values() {
        let result = diff_test(
            "\
arc.module @m {
  arc.func @main() -> i64 {
  ^entry:
    %a = arc.const 5 : i64
    %b = arc.const 10 : i64
    %c = arc.sub %a, %b : i64
    arc.return %c : i64
  }
}
",
        )
        .unwrap();
        assert!(result.match_);
        assert_eq!(result.interp_result, Some(-5));
    }

    #[test]
    fn diff_zero() {
        let result = diff_test(
            "\
arc.module @m {
  arc.func @main() -> i64 {
  ^entry:
    %a = arc.const 0 : i64
    arc.return %a : i64
  }
}
",
        )
        .unwrap();
        assert!(result.match_);
        assert_eq!(result.interp_result, Some(0));
    }

    #[test]
    fn diff_large_value() {
        let result = diff_test(
            "\
arc.module @m {
  arc.func @main() -> i64 {
  ^entry:
    %a = arc.const 1000000000 : i64
    %b = arc.const 2000000000 : i64
    %c = arc.add %a, %b : i64
    arc.return %c : i64
  }
}
",
        )
        .unwrap();
        assert!(result.match_);
        assert_eq!(result.interp_result, Some(3000000000));
    }
}
